music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^success/$', views.success_page, name='success_page'),
    url(r'^not_valid/$', views.not_valid, name='not_valid'),
    url(r'^img_upload/$', views.img_upload, name='img_upload'), #img upload page page
    url(r'^img_select/$', views.img_select, name='img_select'), #img upload page page
    url(r'^enter_tag/$', views.enter_tag, name='enter_tag'), #img upload page page
   
    ]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('music.urls')),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Images(models.Model):
    
    username = models.CharField(max_length=250)
    tagg = models.CharField(max_length=500)
    ans = models.CharField(max_length=50)
    pass_img = models.FileField()
    optical_img = models.FileField()
    other_img1 = models.FileField()
    other_img2 = models.FileField()
    other_img3 = models.FileField()
    other_img4 = models.FileField()
    other_img5 = models.FileField()
    other_img6 = models.FileField()
    other_img7 = models.FileField()
    other_img8 = models.FileField()
    
    def __str__(self):
        return self.username + ' - ' + self.tagg 

music/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import UserForm
import cv2
from .models import Images




def img_upload(request):
    return render(request, 'music/img_upload.html', {'apna_var' : 'a',})

def enter_tag(request):
    if request.method == "POST":
        tagg = request.POST['tagg'] #or pass values in enter tag
        username = request.POST['username']
        selected_image = request.POST['selected_image']
        result=get_object_or_404(Images, username=username)
       
        if selected_image == "pass_img" and tagg == result.tagg:
            
            return render(request, 'music/success.html', { 'tagg' : tagg, 'username' : username , 'user' : user})
        else:
            return render(request, 'music/not_valid.html')
    else:
        return render(request, 'music/login.html')#return render(request, 'music/enter_tag.html', {'selected_image' : '/media/4.jpg',})


def img_select(request):
    if request.method == "POST":
        username = request.POST['username'] #or pass values in enter tag
        #usernamee = "me"
        option= request.POST['img1']
        result=get_object_or_404(Images, username=username)
        return render(request, 'music/enter_tag.html', {'image' : result, 'option' : option })
    else:
    	return render(request, 'music/login.html')

def index(request):
    return render(request, 'music/index.html')
    


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        #get pk where username=username
        result=get_object_or_404(Images, username=username)
        #result=Images.objects.get(username=username)
        if result:
            #return render(request, 'music/login1.html', {'error_message': result.tagg})
            return render(request, 'music/img_select.html', {'image' : result})
        else:
            return render(request, 'music/login.html', {'error_message': 'username is not correct'})
    
    return render(request, 'music/login.html', {'apni_img1' : '/media/1.jpg', 
        })


def success_page(request):
   
    return render(request, 'music/success.html')

def not_valid(request):
   
    return render(request, 'music/not_valid.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #albums = Album.objects.filter(user=request.user)
                return render(request, 'music/success.html')
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)

music/templates/music/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/enter_tag.html
{% if option == "pass_img" %}
	<img src = /media/{{image.pass_img}} height="400">
{% elif option == "other_img1"%}
	<img src = /media/{{image.other_img1}} height="400">
{% elif option == "other_img2"%}
	<img src = /media/{{image.other_img2}} height="400">
{% elif option == "other_img3"%}
	<img src = /media/{{image.other_img3}} height="400">
{% elif option == "other_img4"%}
	<img src = /media/{{image.other_img4}} height="400">
{% elif option == "other_img5"%}
	<img src = /media/{{image.other_img5}} height="400">
{% elif option == "other_img6"%}
	<img src = /media/{{image.other_img6}} height="400">
{% elif option == "other_img7"%}
	<img src = /media/{{image.other_img7}} height="400">
{% else%}
	<img src = /media/{{image.other_img8}} height="400">
{% endif %}


<form action="{% url 'music:enter_tag'%}" method="post" enctype="multipart/form-data" id="form1">
	{% csrf_token %}
	enter tag of this image:
  <input id="tagg" maxlength="30" name="tagg" type="password">
  <input id="id_username" maxlength="30" name="username" type="password" value="{{image.username}}">
  <input id="id_selected_image" maxlength="30" name="selected_image" type="password" value="{{option}}">
    <button type="submit" form="form1" value="Submit">Submit</button>

</form>

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/img_select.html
<html>
<head>
	<style type="text/css">
	img {
    -webkit-filter: blur(16px); /* Safari 6.0 - 9.0 */
    filter: blur(16px);
}
table, th, td {
    border: 1px solid black;

}

</style>


</head>

<img style="-webkit-filter: blur(1px);filter: blur(1px);" src = /media/{{image.optical_img}} height="400">

<form action="{% url 'music:img_select'%}" method="post" enctype="multipart/form-data" id="form1">
	 {% csrf_token %}
   <input id="id_username" maxlength="30" name="username" type="text" value="{{image.username}}">
<br>
tick on your image
<br>
<table >
  <tr>
    <th><img src = /media/{{image.pass_img}} height="200" width="200">
    	<input type="radio" name="img1" value="pass_img" <br></th>
    <th><img src = /media/{{image.other_img1}} height="200" width="200">
    <input type="radio" name="img1" value="other_img1" <br></th> 
    <th><img src = /media/{{image.other_img2}} height="200" width="200">
    <input type="radio" name="img1" value="other_img2" <br></th>
  </tr>
  <tr>
    <td><img src = /media/{{image.other_img3}} height="200" width="200">
    <input type="radio" name="img1" value="other_img3" <br></td>
    <td><img src = /media/{{image.other_img4}} height="200" width="200">
    <input type="radio" name="img1" value="other_img4" <br></td>
    <td><img src = /media/{{image.other_img5}} height="200" width="200">
    <input type="radio" name="img1" value="other_img5" <br></td>
  </tr>
  <tr>
    <td><img src = /media/{{image.other_img6}} height="200" width="200">
    <input type="radio" name="img1" value="other_img6" <br></td>
    <td><img src = /media/{{image.other_img7}} height="200" width="200">
    <input type="radio" name="img1" value="other_img7" <br></td>
    <td><img src = /media/{{image.other_img8}} height="200" width="200">
    <input type="radio" name="img1" value="other_img8" <br></td>
  </tr>
 
</table>
<button type="submit" form="form1" value="Submit">Submit</button>
</form>







<!--<img src = {{ apni_img1}} height="200" width="200">-->
<h1>hi
</h1>

{% if image %}
<p> <strong>passed variable is in if {{image.username}}</strong></p>
{% else %}
<p> <strong> passed variable is in else {{apni_img1}} </strong></p>
{% endif %}

music/templates/music/img_upload.html
<html>
<head>
	<style type="text/css">img {
    -webkit-filter: blur(10px); /* Safari 6.0 - 9.0 */
    filter: blur(10px);
}
</style>
</head>
<img src = "/media/5.jpg" height="400">
<h1>hi
</h1>

{% if apna_var %}
<p> <strong>passed variable is in if {{apna_var}}</strong></p>
{% else %}
<p> <strong> passed variable is in else {{apna_var}} </strong></p>
{% endif %}
</html>

music/templates/music/index.html
this is index page

music/templates/music/login.html
{% block body %}

                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form  role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                       
                            
                                Username:
                            
                           
                                <input id="id_username" maxlength="30" name="username" type="text">
                        
                      <br>
                         
                           <button type="submit" class="btn btn-success">Submit</button>
                            
                    </form>
               
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                
{% endblock %}

music/templates/music/login1.html
{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/not_valid.html
not valid data

music/templates/music/register.html
{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'music:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/success.html
success

{% if tagg %}
<p> <strong>enter optn passed variable is in if {{tagg}}</strong></p>
{% else %}
<p> <strong> enter optn passed variable is in else {{tagg}} </strong></p>
{% endif %}

{% if username %}
<p> <strong>enter optn passed variable is in if {{username}}</strong></p>
{% else %}
<p> <strong> enter optn passed variable is in else {{username}} </strong></p>
{% endif %}

{% if user %}
<p> <strong>enter optn passed variable is in if {{user}}</strong></p>
{% else %}
<p> <strong> enter optn passed variable is in else {{user}} </strong></p>
{% endif %}